sudo: required
language: node_js
services:
- docker
node_js:
- node
before_install:
- curl -L http://releases.rancher.com/compose/v0.8.6/rancher-compose-linux-amd64-v0.8.6.tar.gz -o rancher-compose.tar.gz
- tar -zxvf rancher-compose.tar.gz && mv ./rancher-compose-v0.8.6/rancher-compose ./rancher-compose && rm -fr ./rancher-compose-v0.8.6 && rm ./rancher-compose.tar.gz
- npm install -g gulp
- npm install -g bower
install:
- npm install
- bower install
script:
- gulp
after_success:
- docker build -t krack/lesloupsgourmands:test .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push krack/lesloupsgourmands:test
- ./rancher-compose -p lesloupsgourmands-dev -f docker-compose.yml -r rancher-compose.yml rm -f
- ./rancher-compose -p lesloupsgourmands-dev -f docker-compose.yml -r rancher-compose.yml -e dev.env up -d
before_deploy:
- cd dist && zip -ro ../lesloupsgourmands.zip * && cd ..
- docker tag krack/lesloupsgourmands:test krack/lesloupsgourmands:${TRAVIS_TAG}
- docker tag krack/lesloupsgourmands:${TRAVIS_TAG} krack/lesloupsgourmands:latest
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push krack/lesloupsgourmands:${TRAVIS_TAG}
- docker push krack/lesloupsgourmands:latest
- ./rancher-compose -p lesloupsgourmands-prod -f docker-compose.yml -r rancher-compose.yml rm -f
- ./rancher-compose -p lesloupsgourmands-prod -f docker-compose.yml -r rancher-compose.yml -e prod.env up -d
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
