version: '2'
services:  
  load-balancer:
    ports:
    - ${HOST_PORT}
    image: rancher/load-balancer-service
    links:
    - web:web
    labels:
      proxy_url: ${EXPOSE_URL}
  web:
    labels:
      io.rancher.container.pull_image: always
    image: krack/lesloupsgourmands:${TAG}